### PR TITLE
Add regex match timeout

### PR DESCRIPTION
**Pull request by ChengTian**
parent https://github.com/aspnet/FileSystem/issues/106

@davidfowl @Eilon @troydai

### CODE REVIEW

**Comment by Eilon** [comment]
@blowdart to review.

This looks fine to me.

**Comment by blowdart** [comment]
Fine by me

**Comment by blowdart** [comment]
Fine by me

**Comment by ChengTian** [comment]
Thanks! I assume the second "Fine by me" is for https://github.com/aspnet/dnx/pull/2457 :smile:

**Pull request merged**
