### PR TITLE
Target net45 in Globbing package

### PR DESCRIPTION
**Pull request by BrennanConroy**
https://github.com/aspnet/FileSystem/issues/212

### CODE REVIEW

**Comment by BrennanConroy** [comment]
@muratg @Eilon @anurse

**Comment by Eilon** [comment]
:shipit:

**Comment by pranavkm** [comment]
Does this build in Travis? Do we need a reference assembly pack for `net45`?

**Comment by muratg** [comment]
Looks like it failed on Travis.

**Comment by BrennanConroy** [comment]
Yeah, working with @pranavkm to fix it.

**Comment by anurse** [comment]
Assuming green builds: :shipit:

**Pull request merged**
