### PR TITLE
Update interfaces

### PR DESCRIPTION
**Pull request by troydai**
Addressing https://github.com/aspnet/FileSystem/issues/57

@DamianEdwards anything else need to be addressed?

### CODE REVIEW

**Comment by DamianEdwards** [comment]
Looks good to me

**Comment by troydai** [comment]
Can't check in right now. Pending on __internialization__ of FileSystemGlobbing in runtime. Otherwise the test will always fail because the runtime pull in old version of FileSystemGlobbing.

**Comment by troydai** [comment]
Oh, yeah. With the globbing be internalized in runtime. This PR can be merged as soon as there is a new KRE published.

**Comment by DamianEdwards** [comment]
I'll wait here then...

**Comment by troydai** [comment]
Changes pushed, build passed, and the package is on the volatile feed. Enjoy.

**Pull request merged**
