### PR TITLE
Make 'IFileProvider.GetDirectoryContents' async

### PR DESCRIPTION
**Pull request by hishamco**
@Praburaj based on your issue #30

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@hishamco__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.msopentech.com.
    </span>

TTYL, MSOTBOT;

**Comment by msotclas** [comment]
__@hishamco__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Comment by Praburaj** [comment]
Thanks @hishamco for the PR.

@lodejard @muratg @glennc - Did we get a chance to discuss about this work item? Are we okay doing this?

**Comment by davidfowl** [comment]
I don't think we approved this bug.

**Comment by davidfowl** [comment]
Closing this because we haven't decided to make anything async. We'll need to re-evaluate this issue and decide if we're going to do it.

**Comment by hishamco** [comment]
Ok @davidfowl

**Pull request closed without merging**
