### PR TITLE
Migrate tests/samples/tools to portable

### PR DESCRIPTION
**Pull request by pakrym**
@davidfowl @anurse @pranavkm

### CODE REVIEW

**Comment by anurse** [comment]
:shipit: on green builds

**Comment by MartinJohns** [comment]
@anurse : For understanding and curiosity, what does "ship it on green builds" mean? I see it was merged, but below the merge message I see

```
0 of 2 checks passed
continuous-integration/appveyor/pr AppVeyor build failed
continuous-integration/travis-ci/pr The Travis CI build is in progress
```

**Comment by pakrym** [comment]
@MartinJohns we decided to merge it and test on our internal CI because there is an issue with version of `dotnet-test-xunit` that travis and appveyor hit which would take some time to go away.

**Comment by MartinJohns** [comment]
I see, thanks for clarification!

**Comment by anurse** [comment]
And I'm working from home today so I'm not as much in-the-loop on these things :P.

**Pull request merged**
