### PR TITLE
Remove RestrictedFileNames checks

### PR DESCRIPTION
**Pull request by Praburaj**
Fixes: https://github.com/aspnet/FileSystem/issues/37

@blowdart

### CODE REVIEW

**Comment by Praburaj** [comment]
@muratg

**Comment by muratg** [comment]
Did you verify that no one uses this?  

:shipit:

**Comment by Praburaj** [comment]
yeah. This is internal and no one should be impacted.

**Comment by Praburaj** [comment]
Merged: https://github.com/aspnet/FileSystem/commit/ee72e744ffa8294b7e7caa9a99052da363e5ddea

**Pull request closed without merging**
